dist: bionic
sudo: required

language: minimal

env:
  - NODE_VERSION=16 # EOL: April 2024 
  - NODE_VERSION=14 # EOL: April 2023
  - NODE_VERSION=12 # EOL: April 2022

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | sudo -E bash -
  - sudo apt-get install -y nodejs

before_script:
  - ./build-package
  - sudo dpkg -i deb/*.deb

script:
  - ./tests.sh
  - sudo systemctl --full status thelounge.service

deploy:
  - provider: releases
    repo: thelounge/thelounge-deb
    api_key:
      secure: cTQSyxl5tLt0ogK/ILtznqU3NCG+BIVi4rCm6LWKht9ilInMb0qq+psx1uc1SyKMMausk9znc/bUKAh3JUGRUgqSZAG0vWGvRqvv23fs9uh0YMoVmixW72hRWeI3lZlYL735/MYZDFf4UTTVPuvKm6slxgDvrDyAW37L2VmDl6tnblhOR5QbKFXSs6E2k9K+XU7vAW9xjuS4qJ0PDkpIdJCUloH4vMBZ9KuFZG0CjkobwdqZTqmhrd8tOprs1c6tEBOWGNQsAC4rYfRXrnZ+y9B/pybN7LGJlONfjSaiszlfbNSm2hTK8Tsg2P6q/kg/SLVlGsaiqKfxB15+3kzSRXXdoCNI4XuhKx2+Vryj5gZ2T5d3KqiL1Zv7qV3PgNaiuh4ITt0nIaH0ilDmWKPYLzmOs/V0dhvtQIC17LXip3O5E3Owv+olo1zi/nhjQydxf6CkuexFnrjK4TaVyC02HSaLmP6i9fGBZNbNKHe6JuB8LBWi+snoJJulcjyxnyZqASrE/sSRqVLwDZMZtmLx1yBDrCCP2AASl4LsxMbAGu0iA/YGFOXOoyytfVAc3FDddpWMnB7s4bZTQfZOy5wDSPyCA/BzFsHMXdHIq3B95TrbjWtoqiuwf0e2CG+23pl95i+5aItY7BrCOJ5O7F26M3Frw3y/3DkXYfQ7mUymx/0=
    file: deb/*.deb
    file_glob: true
    skip_cleanup: true
    on:
      condition: "$NODE_VERSION = 12"
      repo: thelounge/thelounge-deb
      tags: true

  - provider: releases
    repo: thelounge/thelounge
    api_key:
      secure: cTQSyxl5tLt0ogK/ILtznqU3NCG+BIVi4rCm6LWKht9ilInMb0qq+psx1uc1SyKMMausk9znc/bUKAh3JUGRUgqSZAG0vWGvRqvv23fs9uh0YMoVmixW72hRWeI3lZlYL735/MYZDFf4UTTVPuvKm6slxgDvrDyAW37L2VmDl6tnblhOR5QbKFXSs6E2k9K+XU7vAW9xjuS4qJ0PDkpIdJCUloH4vMBZ9KuFZG0CjkobwdqZTqmhrd8tOprs1c6tEBOWGNQsAC4rYfRXrnZ+y9B/pybN7LGJlONfjSaiszlfbNSm2hTK8Tsg2P6q/kg/SLVlGsaiqKfxB15+3kzSRXXdoCNI4XuhKx2+Vryj5gZ2T5d3KqiL1Zv7qV3PgNaiuh4ITt0nIaH0ilDmWKPYLzmOs/V0dhvtQIC17LXip3O5E3Owv+olo1zi/nhjQydxf6CkuexFnrjK4TaVyC02HSaLmP6i9fGBZNbNKHe6JuB8LBWi+snoJJulcjyxnyZqASrE/sSRqVLwDZMZtmLx1yBDrCCP2AASl4LsxMbAGu0iA/YGFOXOoyytfVAc3FDddpWMnB7s4bZTQfZOy5wDSPyCA/BzFsHMXdHIq3B95TrbjWtoqiuwf0e2CG+23pl95i+5aItY7BrCOJ5O7F26M3Frw3y/3DkXYfQ7mUymx/0=
    file: deb/*.deb
    file_glob: true
    skip_cleanup: true
    on:
      condition: "$NODE_VERSION = 12"
      repo: thelounge/thelounge-deb
      tags: true
